services:
  aicodinggame.webapi:
    image: aicodinggame.webapi
    build:
      context: .
      dockerfile: AICodingGame.WebAPI/Dockerfile
    ports:
      - "80:8080"
    depends_on: 
      - aicodinggame.db
  
  aicodinggame.db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RobotDatabase
    ports:
      - "5432:5432"